#!/bin/zsh

#
# Install:
#   Add this bash as excutable file
#   dependent on nmap tool, you should install it first.
#   eg: put it to ~/bin, then `chmod +x nmap_and_ssh_my_server`, and you can excute it.
# Usage: 
#   $ ~/bin/nmap_and_ssh_my_server
#

#get local network eg: 192.168.2.1/24
get-local-net() { 
  ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p' | awk '{print substr($0,0,9) ".0/24"}'
}

nmap -sn `get-local-net`
ssh_my_server
